# Generated by Django 5.2.1 on 2025-05-28 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TourPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.PositiveIntegerField(help_text='Duration in days')),
                ('location', models.CharField(max_length=255)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='tour_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('included_meals', models.CharField(blank=True, help_text='Comma separated: breakfast, lunch, dinner', max_length=255)),
                ('transportation', models.CharField(blank=True, max_length=255)),
                ('attractions', models.TextField(blank=True, help_text='Comma-separated attractions')),
                ('tour_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to='tours.tourpackage')),
            ],
            options={
                'ordering': ['day_number'],
                'unique_together': {('tour_package', 'day_number')},
            },
        ),
    ]
